/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from 'src/assets/images/navbar_Vector.png';
import TheViewImage from 'src/assets/images/navbar_The_View.png';
import { styled } from '@mui/material/styles';
import Button1 from 'src/components/Button1/Button1';

const Navbar1 = styled('div')({
  backgroundColor: `rgba(68, 68, 68, 1)`,
  boxShadow: `0px 4px 8px rgba(0, 0, 0, 0.08)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `8px 16px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const IcRoundArrowBack = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector = styled('img')({
  height: `15.17px`,
  width: `15.58px`,
  position: `absolute`,
  left: `4px`,
  top: `4px`,
});

const Frame5 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 16px`,
});

const TheView = styled('img')({
  height: `19.42px`,
  width: `109.76px`,
  margin: `0px`,
});

const ByHektaKarya = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `4px 0px 0px 0px`,
});

const Frame4 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px 0px 0px 16px`,
});

const Frame2 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 16px`,
});

const Button2 = styled(Button1)(({ theme }) => ({
  margin: `0px`,
}));

const Button3 = styled(Button1)(({ theme }) => ({
  margin: `0px 0px 0px 16px`,
}));

function Navbar(props) {
  return (
    <Navbar1 className={props.className}>
      <IcRoundArrowBack>
        <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
      </IcRoundArrowBack>
      <Frame5>
        <TheView src={TheViewImage} loading="lazy" alt={'The View'} />
        <ByHektaKarya>{`by Hekta Karya`}</ByHektaKarya>
      </Frame5>
      <Frame4></Frame4>
      <Frame2>
        <Button2 />
        <Button3 />
      </Frame2>
    </Navbar1>
  );
}

export default Navbar;
